sudo: required
language: node_js
node_js:
  - "10"
before_script:
  - npm install pm2 -g
deploy:
  - provider: azure_web_apps
    site: kcd-web-live-dev
    slot: kcd-web-live-dev-staging
    verbose: true
    on: develop
  - provider: azure_web_apps
    site: kcd-web-preview-dev
    slot: kcd-web-preview-dev-staging
    verbose: true
    on: develop
  - provider: azure_web_apps
    site: kcd-web-live-master
    slot: kcd-web-live-master-staging
    verbose: true
    on: master
  - provider: azure_web_apps
    site: kcd-web-preview-master
    slot: kcd-web-preview-master-staging
    verbose: true
    on: master
