sudo: required
language: node_js
node_js:
  - "10"
jobs:
  include:
    - stage: "Tests"
      name: "ESLint"
      script: npm run eslint
    - stage: "Tests"
      name: "Test"
      script: npm test
    - stage: "Deployment"
      if: branch = master OR branch = develop
      before_install: chmod +rx .travis/deploy.sh
      script: .travis/deploy.sh
