sudo: required
language: node_js
node_js:
  - "14"
jobs:
  include:
    - stage: "Tests"
      name: "ESLint"
      script: npm run eslint
    - stage: "Tests"
      name: "Test"
      script: npm test
    - stage: "Deployment"
      if: type != pull_request AND (branch = master OR branch = develop)
      script: gulp build
      before_install: chmod +rx .travis/deploy.sh
      script: .travis/deploy.sh
