sudo: required
language: node_js
node_js:
  - "10"
deploy:
  - provider: azure_web_apps
    site: kcd-web-live-dev
    slot: kcd-web-live-dev-staging
    verbose: true
    on: develop
  - provider: azure_web_apps
    site: kcd-web-preview-dev
    slot: kcd-web-live-dev-staging
    verbose: true
    on: develop
  - provider: azure_web_apps
    site: kcd-web-live-master
    slot: kcd-web-live-dev-staging
    verbose: true
    on: master
  - provider: azure_web_apps
    site: kcd-web-preview-master
    slot: kcd-web-live-dev-staging
    verbose: true
    on: master
