# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name:  Deploy to nav preview-dev

on:
  push:
    branches:
      - feature/KKD-103
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: '14.15.1'

    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kkd-web-preview-dev'
        slot-name: 'staging'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6bd499d73f3c4b778a859c7f79f9d762 }}
        package: .